/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ForgotPasswordRouteImport } from './routes/forgotPassword'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UseCasesSlugRouteImport } from './routes/use-cases.$slug'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as ResetPasswordTokenRouteImport } from './routes/resetPassword.$token'
import { Route as PlatformSlugRouteImport } from './routes/platform.$slug'
import { Route as CompanySlugRouteImport } from './routes/company.$slug'

const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgotPassword',
  path: '/forgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesSlugRoute = UseCasesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UseCasesRoute,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/resetPassword/$token',
  path: '/resetPassword/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSlugRoute = PlatformSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlatformRoute,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CompanyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgotPassword': typeof ForgotPasswordRoute
  '/platform': typeof PlatformRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/use-cases': typeof UseCasesRouteWithChildren
  '/company/$slug': typeof CompanySlugRoute
  '/platform/$slug': typeof PlatformSlugRoute
  '/resetPassword/$token': typeof ResetPasswordTokenRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgotPassword': typeof ForgotPasswordRoute
  '/platform': typeof PlatformRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/use-cases': typeof UseCasesRouteWithChildren
  '/company/$slug': typeof CompanySlugRoute
  '/platform/$slug': typeof PlatformSlugRoute
  '/resetPassword/$token': typeof ResetPasswordTokenRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgotPassword': typeof ForgotPasswordRoute
  '/platform': typeof PlatformRouteWithChildren
  '/resources': typeof ResourcesRouteWithChildren
  '/use-cases': typeof UseCasesRouteWithChildren
  '/company/$slug': typeof CompanySlugRoute
  '/platform/$slug': typeof PlatformSlugRoute
  '/resetPassword/$token': typeof ResetPasswordTokenRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/use-cases/$slug': typeof UseCasesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/dashboard'
    | '/forgotPassword'
    | '/platform'
    | '/resources'
    | '/use-cases'
    | '/company/$slug'
    | '/platform/$slug'
    | '/resetPassword/$token'
    | '/resources/$slug'
    | '/use-cases/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/dashboard'
    | '/forgotPassword'
    | '/platform'
    | '/resources'
    | '/use-cases'
    | '/company/$slug'
    | '/platform/$slug'
    | '/resetPassword/$token'
    | '/resources/$slug'
    | '/use-cases/$slug'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/dashboard'
    | '/forgotPassword'
    | '/platform'
    | '/resources'
    | '/use-cases'
    | '/company/$slug'
    | '/platform/$slug'
    | '/resetPassword/$token'
    | '/resources/$slug'
    | '/use-cases/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  ResourcesRoute: typeof ResourcesRouteWithChildren
  UseCasesRoute: typeof UseCasesRouteWithChildren
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotPassword': {
      id: '/forgotPassword'
      path: '/forgotPassword'
      fullPath: '/forgotPassword'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/$slug': {
      id: '/use-cases/$slug'
      path: '/$slug'
      fullPath: '/use-cases/$slug'
      preLoaderRoute: typeof UseCasesSlugRouteImport
      parentRoute: typeof UseCasesRoute
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resetPassword/$token': {
      id: '/resetPassword/$token'
      path: '/resetPassword/$token'
      fullPath: '/resetPassword/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/$slug': {
      id: '/platform/$slug'
      path: '/$slug'
      fullPath: '/platform/$slug'
      preLoaderRoute: typeof PlatformSlugRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/company/$slug': {
      id: '/company/$slug'
      path: '/$slug'
      fullPath: '/company/$slug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof CompanyRoute
    }
  }
}

interface CompanyRouteChildren {
  CompanySlugRoute: typeof CompanySlugRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanySlugRoute: CompanySlugRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

interface PlatformRouteChildren {
  PlatformSlugRoute: typeof PlatformSlugRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformSlugRoute: PlatformSlugRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface UseCasesRouteChildren {
  UseCasesSlugRoute: typeof UseCasesSlugRoute
}

const UseCasesRouteChildren: UseCasesRouteChildren = {
  UseCasesSlugRoute: UseCasesSlugRoute,
}

const UseCasesRouteWithChildren = UseCasesRoute._addFileChildren(
  UseCasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PlatformRoute: PlatformRouteWithChildren,
  ResourcesRoute: ResourcesRouteWithChildren,
  UseCasesRoute: UseCasesRouteWithChildren,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
